[
   {
   "state":"U.S.",
   "stateAbbr":"US",
   "attendOrVisit":"45.2%",
   "performCreate":"32.7%",
   "read":"39.9%",
   "device":"55.3%"
   },
   {
   "state":"Alabama",
   "stateAbbr":"AL",
   "attendOrVisit":"27.3%",
   "performCreate":"22.0%",
   "read":"23.7%",
   "device":"37.1%"
   },
   {
   "state":"Alaska",
   "stateAbbr":"AK",
   "attendOrVisit":"48.8%",
   "performCreate":"44.2%",
   "read":"55.1%",
   "device":"71.2%"
   },
   {
   "state":"Arizona",
   "stateAbbr":"AZ",
   "attendOrVisit":"56.4%",
   "performCreate":"35.6%",
   "read":"39.2%",
   "device":"59.5%"
   },
   {
   "state":"Arkansas",
   "stateAbbr":"AR",
   "attendOrVisit":"36.6%",
   "performCreate":"32.3%",
   "read":"30.0%",
   "device":"44.2%"
   },
   {
   "state":"California",
   "stateAbbr":"CA",
   "attendOrVisit":"42.8%",
   "performCreate":"30.9%",
   "read":"32.2%",
   "device":"57.5%"
   },
   {
   "state":"Colorado",
   "stateAbbr":"CO",
   "attendOrVisit":"65.1%",
   "performCreate":"43.7%",
   "read":"54.3%",
   "device":"70.8%"
   },
   {
   "state":"Connecticut",
   "stateAbbr":"CT",
   "attendOrVisit":"56.4%",
   "performCreate":"37.4%",
   "read":"40.7%",
   "device":"57.5%"
   },
   {
   "state":"Delaware",
   "stateAbbr":"DE",
   "attendOrVisit":"44.5%",
   "performCreate":"33.6%",
   "read":"37.8%",
   "device":"43.9%"
   },
   {
   "state":"District of Columbia",
   "stateAbbr":"DC",
   "attendOrVisit":"56.6%",
   "performCreate":"42.9%",
   "read":"47.7%",
   "device":"59.5%"
   },
   {
   "state":"Florida",
   "stateAbbr":"FL",
   "attendOrVisit":"38.1%",
   "performCreate":"23.2%",
   "read":"30.5%",
   "device":"47.7%"
   },
   {
   "state":"Georgia",
   "stateAbbr":"GA",
   "attendOrVisit":"43.9%",
   "performCreate":"26.2%",
   "read":"45.3%",
   "device":"58.3%"
   },
   {
   "state":"Hawaii",
   "stateAbbr":"HI",
   "attendOrVisit":"39.4%",
   "performCreate":"37.3%",
   "read":"27.8%",
   "device":"42.4%"
   },
   {
   "state":"Idaho",
   "stateAbbr":"ID",
   "attendOrVisit":"47.4%",
   "performCreate":"35.7%",
   "read":"47.0%",
   "device":"52.3%"
   },
   {
   "state":"Illinois",
   "stateAbbr":"IL",
   "attendOrVisit":"49.4%",
   "performCreate":"36.2%",
   "read":"44.8%",
   "device":"64.1%"
   },
   {
   "state":"Indiana",
   "stateAbbr":"IN",
   "attendOrVisit":"37.2%",
   "performCreate":"36.4%",
   "read":"39.9%",
   "device":"57.0%"
   },
   {
   "state":"Iowa",
   "stateAbbr":"IA",
   "attendOrVisit":"41.7%",
   "performCreate":"37.6%",
   "read":"35.6%",
   "device":"46.2%"
   },
   {
   "state":"Kansas",
   "stateAbbr":"KS",
   "attendOrVisit":"41.0%",
   "performCreate":"30.3%",
   "read":"40.7%",
   "device":"59.1%"
   },
   {
   "state":"Kentucky",
   "stateAbbr":"KY",
   "attendOrVisit":"40.5%",
   "performCreate":"25.2%",
   "read":"37.2%",
   "device":"46.4%"
   },
   {
   "state":"Louisiana",
   "stateAbbr":"LA",
   "attendOrVisit":"29.7%",
   "performCreate":"27.4%",
   "read":"28.9%",
   "device":"48.3%"
   },
   {
   "state":"Maine",
   "stateAbbr":"ME",
   "attendOrVisit":"42.7%",
   "performCreate":"45.8%",
   "read":"44.6%",
   "device":"58.4%"
   },
   {
   "state":"Maryland",
   "stateAbbr":"MD",
   "attendOrVisit":"48.9%",
   "performCreate":"34.2%",
   "read":"44.6%",
   "device":"56.0%"
   },
   {
   "state":"Massachusetts",
   "stateAbbr":"MA",
   "attendOrVisit":"51.0%",
   "performCreate":"35.6%",
   "read":"50.0%",
   "device":"52.0%"
   },
   {
   "state":"Michigan",
   "stateAbbr":"MI",
   "attendOrVisit":"50.1%",
   "performCreate":"35.6%",
   "read":"42.7%",
   "device":"52.1%"
   },
   {
   "state":"Minnesota",
   "stateAbbr":"MN",
   "attendOrVisit":"56.2%",
   "performCreate":"38.0%",
   "read":"50.7%",
   "device":"60.0%"
   },
   {
   "state":"Mississippi",
   "stateAbbr":"MS",
   "attendOrVisit":"28.2%",
   "performCreate":"24.6%",
   "read":"24.3%",
   "device":"46.3%"
   },
   {
   "state":"Missouri",
   "stateAbbr":"MO",
   "attendOrVisit":"44.4%",
   "performCreate":"35.6%",
   "read":"42.2%",
   "device":"54.9%"
   },
   {
   "state":"Montana",
   "stateAbbr":"MT",
   "attendOrVisit":"52.8%",
   "performCreate":"46.7%",
   "read":"57.8%",
   "device":"65.1%"
   },
   {
   "state":"Nebraska",
   "stateAbbr":"NE",
   "attendOrVisit":"46.8%",
   "performCreate":"47.8%",
   "read":"43.3%",
   "device":"52.3%"
   },
   {
   "state":"Nevada",
   "stateAbbr":"NV",
   "attendOrVisit":"34.9%",
   "performCreate":"24.8%",
   "read":"26.5%",
   "device":"50.3%"
   },
   {
   "state":"New Hampshire",
   "stateAbbr":"NH",
   "attendOrVisit":"51.6%",
   "performCreate":"45.4%",
   "read":"47.7%",
   "device":"63.6%"
   },
   {
   "state":"New Jersey",
   "stateAbbr":"NJ",
   "attendOrVisit":"42.3%",
   "performCreate":"25.8%",
   "read":"35.9%",
   "device":"51.5%"
   },
   {
   "state":"New Mexico",
   "stateAbbr":"NM",
   "attendOrVisit":"47.4%",
   "performCreate":"35.6%",
   "read":"42.4%",
   "device":"60.4%"
   },
   {
   "state":"New York",
   "stateAbbr":"NY",
   "attendOrVisit":"48.8%",
   "performCreate":"28.9%",
   "read":"43.0%",
   "device":"56.1%"
   },
   {
   "state":"North Carolina",
   "stateAbbr":"NC",
   "attendOrVisit":"41.4%",
   "performCreate":"29.7%",
   "read":"34.4%",
   "device":"48.1%"
   },
   {
   "state":"North Dakota",
   "stateAbbr":"ND",
   "attendOrVisit":"55.5%",
   "performCreate":"39.5%",
   "read":"40.4%",
   "device":"56.8%"
   },
   {
   "state":"Ohio",
   "stateAbbr":"OH",
   "attendOrVisit":"45.4%",
   "performCreate":"37.8%",
   "read":"44.4%",
   "device":"64.7%"
   },
   {
   "state":"Oklahoma",
   "stateAbbr":"OK",
   "attendOrVisit":"40.9%",
   "performCreate":"31.5%",
   "read":"39.6%",
   "device":"47.3%"
   },
   {
   "state":"Oregon",
   "stateAbbr":"OR",
   "attendOrVisit":"65.9%",
   "performCreate":"48.5%",
   "read":"66.2%",
   "device":"72.4%"
   },
   {
   "state":"Pennsylvania",
   "stateAbbr":"PA",
   "attendOrVisit":"43.4%",
   "performCreate":"40.3%",
   "read":"42.4%",
   "device":"53.2%"
   },
   {
   "state":"Rhode Island",
   "stateAbbr":"RI",
   "attendOrVisit":"51.0%",
   "performCreate":"33.5%",
   "read":"42.6%",
   "device":"68.2%"
   },
   {
   "state":"South Carolina",
   "stateAbbr":"SC",
   "attendOrVisit":"43.0%",
   "performCreate":"25.4%",
   "read":"48.2%",
   "device":"56.4%"
   },
   {
   "state":"South Dakota",
   "stateAbbr":"SD",
   "attendOrVisit":"49.0%",
   "performCreate":"35.3%",
   "read":"40.3%",
   "device":"56.5%"
   },
   {
   "state":"Tennessee",
   "stateAbbr":"TN",
   "attendOrVisit":"50.3%",
   "performCreate":"38.3%",
   "read":"44.2%",
   "device":"59.4%"
   },
   {
   "state":"Texas",
   "stateAbbr":"TX",
   "attendOrVisit":"43.3%",
   "performCreate":"23.2%",
   "read":"34.0%",
   "device":"51.6%"
   },
   {
   "state":"Utah",
   "stateAbbr":"UT",
   "attendOrVisit":"53.7%",
   "performCreate":"58.0%",
   "read":"59.3%",
   "device":"66.6%"
   },
   {
   "state":"Vermont",
   "stateAbbr":"VT",
   "attendOrVisit":"57.3%",
   "performCreate":"50.9%",
   "read":"58.4%",
   "device":"60.9%"
   },
   {
   "state":"Virginia",
   "stateAbbr":"VA",
   "attendOrVisit":"57.3%",
   "performCreate":"40.0%",
   "read":"44.6%",
   "device":"59.5%"
   },
   {
   "state":"Washington",
   "stateAbbr":"WA",
   "attendOrVisit":"48.5%",
   "performCreate":"51.5%",
   "read":"48.2%",
   "device":"55.8%"
   },
   {
   "state":"West Virginia",
   "stateAbbr":"WV",
   "attendOrVisit":"33.4%",
   "performCreate":"27.4%",
   "read":"38.8%",
   "device":"41.7%"
   },
   {
   "state":"Wisconsin",
   "stateAbbr":"WI",
   "attendOrVisit":"42.0%",
   "performCreate":"40.5%",
   "read":"48.0%",
   "device":"58.8%"
   },
   {
   "state":"Wyoming",
   "stateAbbr":"WY",
   "attendOrVisit":"47.0%",
   "performCreate":"43.6%",
   "read":"44.5%",
   "device":"56.3%"
   }
]